# Generated by Django 5.1.3 on 2025-01-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='код подтверждения'),
        ),
    ]
